/**
 * Every operation in the Clockify API, generated from its published OpenAPI spec.
 *
 * This is the index behind search-clockify-api, and the reason no part of the
 * API is out of reach: anything without a dedicated tool can still be found
 * here and called with call-clockify-api. Data, not behaviour — regenerate it
 * when Clockify publishes new endpoints.
 */

export interface ClockifyOperation {
  method: string;
  path: string;
  summary: string;
  group: string;
}

export const OPERATIONS: ClockifyOperation[] = [
  { method: "GET", path: "/workspaces/{workspaceId}/approval-requests", summary: "Get approval requests", group: "Approval" },
  { method: "POST", path: "/workspaces/{workspaceId}/approval-requests/resubmit-entries-for-approval", summary: "Submit non pending/approved entries/expenses for approval to an existing approval request", group: "Approval" },
  { method: "POST", path: "/workspaces/{workspaceId}/approval-requests/users/{userId}/resubmit-entries-for-approval", summary: "Re-submit rejected/withdrawn entries/expenses for an approval of a user", group: "Approval" },
  { method: "POST", path: "/workspaces/{workspaceId}/approval-requests/users/{userId}/{type}", summary: "Submit approval request for user with type", group: "Approval" },
  { method: "PATCH", path: "/workspaces/{workspaceId}/approval-requests/{approvalRequestId}", summary: "Update an approval request", group: "Approval" },
  { method: "POST", path: "/workspaces/{workspaceId}/approval-requests/{type}", summary: "Submit approval request with type", group: "Approval" },
  { method: "POST", path: "/workspaces/{workspaceId}/approval-requests", summary: "Submit approval request", group: "Approval (Deprecated)" },
  { method: "POST", path: "/workspaces/{workspaceId}/approval-requests/users/{userId}", summary: "Submit approval request for user", group: "Approval (Deprecated)" },
  { method: "POST", path: "/workspaces/{workspaceId}/audit-log", summary: "Generate an audit log report", group: "Audit Log Report" },
  { method: "GET", path: "/workspaces/{workspaceId}/time-off/balance/policy/{policyId}", summary: "Get balances for a policy", group: "Balance" },
  { method: "PATCH", path: "/workspaces/{workspaceId}/time-off/balance/policy/{policyId}", summary: "Update a balance", group: "Balance" },
  { method: "GET", path: "/workspaces/{workspaceId}/time-off/balance/user/{userId}", summary: "Get balance for a user", group: "Balance" },
  { method: "POST", path: "/workspaces/{workspaceId}/time-off/balance/assignment", summary: "Creates a new balance assignment for a user in policy", group: "Balance Assignment" },
  { method: "GET", path: "/workspaces/{workspaceId}/time-off/balance/assignment/user/{userId}/policy/{policyId}", summary: "Get all balance assignments of a user in policy", group: "Balance Assignment" },
  { method: "DELETE", path: "/workspaces/{workspaceId}/time-off/balance/assignment/{balanceAssignmentId}/user/{userId}/policy/{policyId}", summary: "Deletes a specific balance assignment", group: "Balance Assignment" },
  { method: "PUT", path: "/workspaces/{workspaceId}/time-off/balance/assignment/{balanceAssignmentId}/user/{userId}/policy/{policyId}", summary: "Updates a specific balance assignment", group: "Balance Assignment" },
  { method: "GET", path: "/workspaces/{workspaceId}/clients", summary: "Find clients on a workspace", group: "Client" },
  { method: "POST", path: "/workspaces/{workspaceId}/clients", summary: "Add a new client", group: "Client" },
  { method: "DELETE", path: "/workspaces/{workspaceId}/clients/{id}", summary: "Delete a client", group: "Client" },
  { method: "GET", path: "/workspaces/{workspaceId}/clients/{id}", summary: "Get a client by ID", group: "Client" },
  { method: "PUT", path: "/workspaces/{workspaceId}/clients/{id}", summary: "Update a client", group: "Client" },
  { method: "GET", path: "/workspaces/{workspaceId}/custom-fields", summary: "Get custom fields on a workspace", group: "Custom fields" },
  { method: "POST", path: "/workspaces/{workspaceId}/custom-fields", summary: "Create custom fields on a workspace", group: "Custom fields" },
  { method: "DELETE", path: "/workspaces/{workspaceId}/custom-fields/{customFieldId}", summary: "Delete a custom field", group: "Custom fields" },
  { method: "PUT", path: "/workspaces/{workspaceId}/custom-fields/{customFieldId}", summary: "Update custom field on workspace", group: "Custom fields" },
  { method: "GET", path: "/workspaces/{workspaceId}/projects/{projectId}/custom-fields", summary: "Get custom fields on a project", group: "Custom fields" },
  { method: "DELETE", path: "/workspaces/{workspaceId}/projects/{projectId}/custom-fields/{customFieldId}", summary: "Remove custom field from a project", group: "Custom fields" },
  { method: "PATCH", path: "/workspaces/{workspaceId}/projects/{projectId}/custom-fields/{customFieldId}", summary: "Update custom field on a project", group: "Custom fields" },
  { method: "GET", path: "/workspaces/{workspaceId}/entities/created", summary: "Created entities (Experimental)", group: "Entity changes (Experimental)" },
  { method: "GET", path: "/workspaces/{workspaceId}/entities/deleted", summary: "Deleted entities (Experimental)", group: "Entity changes (Experimental)" },
  { method: "GET", path: "/workspaces/{workspaceId}/entities/updated", summary: "Updated entities (Experimental)", group: "Entity changes (Experimental)" },
  { method: "GET", path: "/workspaces/{workspaceId}/expenses", summary: "Get all expenses on a workspace", group: "Expense" },
  { method: "POST", path: "/workspaces/{workspaceId}/expenses", summary: "Create an expense", group: "Expense" },
  { method: "GET", path: "/workspaces/{workspaceId}/expenses/categories", summary: "Get all expense categories", group: "Expense" },
  { method: "POST", path: "/workspaces/{workspaceId}/expenses/categories", summary: "Add an expense category", group: "Expense" },
  { method: "DELETE", path: "/workspaces/{workspaceId}/expenses/categories/{categoryId}", summary: "Delete an expense category", group: "Expense" },
  { method: "PUT", path: "/workspaces/{workspaceId}/expenses/categories/{categoryId}", summary: "Update an expense category", group: "Expense" },
  { method: "PATCH", path: "/workspaces/{workspaceId}/expenses/categories/{categoryId}/status", summary: "Archive an expense category", group: "Expense" },
  { method: "DELETE", path: "/workspaces/{workspaceId}/expenses/{expenseId}", summary: "Delete an expense", group: "Expense" },
  { method: "GET", path: "/workspaces/{workspaceId}/expenses/{expenseId}", summary: "Get an expense by ID", group: "Expense" },
  { method: "PUT", path: "/workspaces/{workspaceId}/expenses/{expenseId}", summary: "Update an expense", group: "Expense" },
  { method: "GET", path: "/workspaces/{workspaceId}/expenses/{expenseId}/files/{fileId}", summary: "Download a receipt", group: "Expense" },
  { method: "POST", path: "/workspaces/{workspaceId}/reports/expenses/detailed", summary: "Generate an expense report", group: "Expense Report" },
  { method: "GET", path: "/workspaces/{workspaceId}/user-groups", summary: "Find all groups on a workspace", group: "Group" },
  { method: "POST", path: "/workspaces/{workspaceId}/user-groups", summary: "Add a new group", group: "Group" },
  { method: "DELETE", path: "/workspaces/{workspaceId}/user-groups/{id}", summary: "Delete a group", group: "Group" },
  { method: "PUT", path: "/workspaces/{workspaceId}/user-groups/{id}", summary: "Update a group", group: "Group" },
  { method: "POST", path: "/workspaces/{workspaceId}/user-groups/{userGroupId}/users", summary: "Add users to a group", group: "Group" },
  { method: "DELETE", path: "/workspaces/{workspaceId}/user-groups/{userGroupId}/users/{userId}", summary: "Remove a user from a group", group: "Group" },
  { method: "GET", path: "/workspaces/{workspaceId}/holidays", summary: "Get holidays on a workspace", group: "Holiday" },
  { method: "POST", path: "/workspaces/{workspaceId}/holidays", summary: "Create a holiday", group: "Holiday" },
  { method: "GET", path: "/workspaces/{workspaceId}/holidays/in-period", summary: "Get holidays in a specific period", group: "Holiday" },
  { method: "DELETE", path: "/workspaces/{workspaceId}/holidays/{holidayId}", summary: "Delete a holiday", group: "Holiday" },
  { method: "PUT", path: "/workspaces/{workspaceId}/holidays/{holidayId}", summary: "Update a holiday", group: "Holiday" },
  { method: "GET", path: "/workspaces/{workspaceId}/invoices", summary: "Get all invoices on a workspace", group: "Invoice" },
  { method: "POST", path: "/workspaces/{workspaceId}/invoices", summary: "Add an invoice", group: "Invoice" },
  { method: "POST", path: "/workspaces/{workspaceId}/invoices/info", summary: "Filter out invoices", group: "Invoice" },
  { method: "GET", path: "/workspaces/{workspaceId}/invoices/settings", summary: "Get invoice settings", group: "Invoice" },
  { method: "PUT", path: "/workspaces/{workspaceId}/invoices/settings", summary: "Change invoice settings", group: "Invoice" },
  { method: "DELETE", path: "/workspaces/{workspaceId}/invoices/{invoiceId}", summary: "Delete an invoice", group: "Invoice" },
  { method: "GET", path: "/workspaces/{workspaceId}/invoices/{invoiceId}", summary: "Get an invoice by ID", group: "Invoice" },
  { method: "PUT", path: "/workspaces/{workspaceId}/invoices/{invoiceId}", summary: "Update an invoice", group: "Invoice" },
  { method: "POST", path: "/workspaces/{workspaceId}/invoices/{invoiceId}/duplicate", summary: "Duplicate an invoice", group: "Invoice" },
  { method: "GET", path: "/workspaces/{workspaceId}/invoices/{invoiceId}/export", summary: "Export an invoice", group: "Invoice" },
  { method: "POST", path: "/workspaces/{workspaceId}/invoices/{invoiceId}/items", summary: "Add item to an invoice", group: "Invoice" },
  { method: "POST", path: "/workspaces/{workspaceId}/invoices/{invoiceId}/items/import", summary: "Import time entries and expenses to an invoice", group: "Invoice" },
  { method: "DELETE", path: "/workspaces/{workspaceId}/invoices/{invoiceId}/items/{order}", summary: "Delete item from an invoice", group: "Invoice" },
  { method: "GET", path: "/workspaces/{workspaceId}/invoices/{invoiceId}/payments", summary: "Get payments for an invoice", group: "Invoice" },
  { method: "POST", path: "/workspaces/{workspaceId}/invoices/{invoiceId}/payments", summary: "Add payment to an invoice", group: "Invoice" },
  { method: "DELETE", path: "/workspaces/{workspaceId}/invoices/{invoiceId}/payments/{paymentId}", summary: "Delete payment from an invoice", group: "Invoice" },
  { method: "PATCH", path: "/workspaces/{workspaceId}/invoices/{invoiceId}/status", summary: "Change an invoice status", group: "Invoice" },
  { method: "GET", path: "/workspaces/{workspaceId}/time-off/policies", summary: "Get policies on a workspace", group: "Policy" },
  { method: "POST", path: "/workspaces/{workspaceId}/time-off/policies", summary: "Create a time off policy", group: "Policy" },
  { method: "DELETE", path: "/workspaces/{workspaceId}/time-off/policies/{id}", summary: "Delete a policy", group: "Policy" },
  { method: "GET", path: "/workspaces/{workspaceId}/time-off/policies/{id}", summary: "Get a time off policy", group: "Policy" },
  { method: "PATCH", path: "/workspaces/{workspaceId}/time-off/policies/{id}", summary: "Change a policy status", group: "Policy" },
  { method: "PUT", path: "/workspaces/{workspaceId}/time-off/policies/{id}", summary: "Update a policy", group: "Policy" },
  { method: "GET", path: "/workspaces/{workspaceId}/projects", summary: "Get all projects on a workspace", group: "Project" },
  { method: "POST", path: "/workspaces/{workspaceId}/projects", summary: "Add a new project", group: "Project" },
  { method: "POST", path: "/workspaces/{workspaceId}/projects/from-template", summary: "Create project from a template", group: "Project" },
  { method: "DELETE", path: "/workspaces/{workspaceId}/projects/{projectId}", summary: "Delete a project from a workspace", group: "Project" },
  { method: "GET", path: "/workspaces/{workspaceId}/projects/{projectId}", summary: "Find a project by ID", group: "Project" },
  { method: "PUT", path: "/workspaces/{workspaceId}/projects/{projectId}", summary: "Update a project on a workspace", group: "Project" },
  { method: "PATCH", path: "/workspaces/{workspaceId}/projects/{projectId}/estimate", summary: "Update project estimate", group: "Project" },
  { method: "PATCH", path: "/workspaces/{workspaceId}/projects/{projectId}/memberships", summary: "Update project memberships", group: "Project" },
  { method: "POST", path: "/workspaces/{workspaceId}/projects/{projectId}/memberships", summary: "Assign/remove users to/from the project", group: "Project" },
  { method: "PATCH", path: "/workspaces/{workspaceId}/projects/{projectId}/template", summary: "Update a project template", group: "Project" },
  { method: "PUT", path: "/workspaces/{workspaceId}/projects/{projectId}/users/{userId}/cost-rate", summary: "Update project user's cost rate", group: "Project" },
  { method: "PUT", path: "/workspaces/{workspaceId}/projects/{projectId}/users/{userId}/hourly-rate", summary: "Update a project user's billable rate", group: "Project" },
  { method: "GET", path: "/workspaces/{workspaceId}/scheduling/assignments/all", summary: "Get all assignments", group: "Scheduling" },
  { method: "POST", path: "/workspaces/{workspaceId}/scheduling/assignments/projects/totals", summary: "Get all scheduled assignments per project", group: "Scheduling" },
  { method: "GET", path: "/workspaces/{workspaceId}/scheduling/assignments/projects/totals/{projectId}", summary: "Get all scheduled assignments on project", group: "Scheduling" },
  { method: "PUT", path: "/workspaces/{workspaceId}/scheduling/assignments/publish", summary: "Publish assignments", group: "Scheduling" },
  { method: "POST", path: "/workspaces/{workspaceId}/scheduling/assignments/recurring", summary: "Create assignment", group: "Scheduling" },
  { method: "DELETE", path: "/workspaces/{workspaceId}/scheduling/assignments/recurring/{assignmentId}", summary: "Delete assignment", group: "Scheduling" },
  { method: "PATCH", path: "/workspaces/{workspaceId}/scheduling/assignments/recurring/{assignmentId}", summary: "Update assignment", group: "Scheduling" },
  { method: "PUT", path: "/workspaces/{workspaceId}/scheduling/assignments/series/{assignmentId}", summary: "Change the recurring period", group: "Scheduling" },
  { method: "POST", path: "/workspaces/{workspaceId}/scheduling/assignments/user-filter/totals", summary: "Get total of users' capacity on workspace", group: "Scheduling" },
  { method: "GET", path: "/workspaces/{workspaceId}/scheduling/assignments/users/{userId}/totals", summary: "Get total capacity of a user", group: "Scheduling" },
  { method: "POST", path: "/workspaces/{workspaceId}/scheduling/assignments/{assignmentId}/copy", summary: "Copy a scheduled assignment", group: "Scheduling" },
  { method: "GET", path: "/workspaces/{workspaceId}/scheduling/assignments/projects/totals", summary: "Get all scheduled assignments per project", group: "Scheduling (Deprecated)" },
  { method: "GET", path: "/shared-reports/{id}", summary: "Generate shared report by ID", group: "Shared Report" },
  { method: "GET", path: "/workspaces/{workspaceId}/shared-reports", summary: "Get all my shared reports", group: "Shared Report" },
  { method: "POST", path: "/workspaces/{workspaceId}/shared-reports", summary: "Create a shared report", group: "Shared Report" },
  { method: "DELETE", path: "/workspaces/{workspaceId}/shared-reports/{id}", summary: "Delete a shared report", group: "Shared Report" },
  { method: "PUT", path: "/workspaces/{workspaceId}/shared-reports/{id}", summary: "Update a shared report", group: "Shared Report" },
  { method: "GET", path: "/workspaces/{workspaceId}/tags", summary: "Find tags on a workspace", group: "Tag" },
  { method: "POST", path: "/workspaces/{workspaceId}/tags", summary: "Add a new tag", group: "Tag" },
  { method: "DELETE", path: "/workspaces/{workspaceId}/tags/{id}", summary: "Delete a tag", group: "Tag" },
  { method: "GET", path: "/workspaces/{workspaceId}/tags/{id}", summary: "Get a tag by ID", group: "Tag" },
  { method: "PUT", path: "/workspaces/{workspaceId}/tags/{id}", summary: "Update a tag", group: "Tag" },
  { method: "GET", path: "/workspaces/{workspaceId}/projects/{projectId}/tasks", summary: "Find tasks on a project", group: "Task" },
  { method: "POST", path: "/workspaces/{workspaceId}/projects/{projectId}/tasks", summary: "Add a new task on a project", group: "Task" },
  { method: "PUT", path: "/workspaces/{workspaceId}/projects/{projectId}/tasks/{id}/cost-rate", summary: "Update a task's cost rate", group: "Task" },
  { method: "PUT", path: "/workspaces/{workspaceId}/projects/{projectId}/tasks/{id}/hourly-rate", summary: "Update a task's billable rate", group: "Task" },
  { method: "DELETE", path: "/workspaces/{workspaceId}/projects/{projectId}/tasks/{taskId}", summary: "Delete a task from a project", group: "Task" },
  { method: "GET", path: "/workspaces/{workspaceId}/projects/{projectId}/tasks/{taskId}", summary: "Get a task by id", group: "Task" },
  { method: "PUT", path: "/workspaces/{workspaceId}/projects/{projectId}/tasks/{taskId}", summary: "Update a task on a project", group: "Task" },
  { method: "POST", path: "/workspaces/{workspaceId}/reports/attendance", summary: "Generate an attendance report", group: "Team Report" },
  { method: "GET", path: "/workspaces/{workspaceId}/templates", summary: "Get all templates on a workspace", group: "Template (Deprecated)" },
  { method: "POST", path: "/workspaces/{workspaceId}/templates", summary: "Create templates on a workspace", group: "Template (Deprecated)" },
  { method: "DELETE", path: "/workspaces/{workspaceId}/templates/{templateId}", summary: "Delete a template", group: "Template (Deprecated)" },
  { method: "GET", path: "/workspaces/{workspaceId}/templates/{templateId}", summary: "Get template by ID on a workspace", group: "Template (Deprecated)" },
  { method: "PATCH", path: "/workspaces/{workspaceId}/templates/{templateId}", summary: "Update a template", group: "Template (Deprecated)" },
  { method: "POST", path: "/workspaces/{workspaceId}/reports/detailed", summary: "Generate a detailed report", group: "Time Entry Report" },
  { method: "POST", path: "/workspaces/{workspaceId}/reports/summary", summary: "Generate a summary report", group: "Time Entry Report" },
  { method: "POST", path: "/workspaces/{workspaceId}/reports/weekly", summary: "Generate a weekly report", group: "Time Entry Report" },
  { method: "POST", path: "/workspaces/{workspaceId}/time-off/policies/{policyId}/requests", summary: "Create a time off request", group: "Time Off" },
  { method: "DELETE", path: "/workspaces/{workspaceId}/time-off/policies/{policyId}/requests/{requestId}", summary: "Delete a time off request", group: "Time Off" },
  { method: "PATCH", path: "/workspaces/{workspaceId}/time-off/policies/{policyId}/requests/{requestId}", summary: "Change a time off request status", group: "Time Off" },
  { method: "POST", path: "/workspaces/{workspaceId}/time-off/policies/{policyId}/users/{userId}/requests", summary: "Create a time off request for a user", group: "Time Off" },
  { method: "POST", path: "/workspaces/{workspaceId}/time-off/requests", summary: "Get all time off requests on a workspace", group: "Time Off" },
  { method: "POST", path: "/workspaces/{workspaceId}/time-entries", summary: "Add a new time entry", group: "Time entry" },
  { method: "POST", path: "/workspaces/{workspaceId}/time-entries/batch", summary: "Get multiple time entries on a workspace", group: "Time entry" },
  { method: "PATCH", path: "/workspaces/{workspaceId}/time-entries/invoiced", summary: "Mark time entries as invoiced", group: "Time entry" },
  { method: "GET", path: "/workspaces/{workspaceId}/time-entries/status/in-progress", summary: "Get all in progress time entries on a workspace", group: "Time entry" },
  { method: "DELETE", path: "/workspaces/{workspaceId}/time-entries/{id}", summary: "Delete a time entry from a workspace", group: "Time entry" },
  { method: "GET", path: "/workspaces/{workspaceId}/time-entries/{id}", summary: "Get a specific time entry on a workspace", group: "Time entry" },
  { method: "PUT", path: "/workspaces/{workspaceId}/time-entries/{id}", summary: "Update time entry on a workspace", group: "Time entry" },
  { method: "DELETE", path: "/workspaces/{workspaceId}/user/{userId}/time-entries", summary: "Delete all time entries for a user on a workspace", group: "Time entry" },
  { method: "GET", path: "/workspaces/{workspaceId}/user/{userId}/time-entries", summary: "Get time entries for a user on a workspace", group: "Time entry" },
  { method: "PATCH", path: "/workspaces/{workspaceId}/user/{userId}/time-entries", summary: "Stop a currently running timer on a workspace for a user", group: "Time entry" },
  { method: "POST", path: "/workspaces/{workspaceId}/user/{userId}/time-entries", summary: "Add a new time entry for another user on workspace", group: "Time entry" },
  { method: "PUT", path: "/workspaces/{workspaceId}/user/{userId}/time-entries", summary: "Bulk edit time entries", group: "Time entry" },
  { method: "POST", path: "/workspaces/{workspaceId}/user/{userId}/time-entries/{id}/duplicate", summary: "Duplicate a time entry", group: "Time entry" },
  { method: "POST", path: "/file/image", summary: "Add a photo", group: "User" },
  { method: "GET", path: "/user", summary: "Get currently logged-in user's info", group: "User" },
  { method: "GET", path: "/workspaces/{workspaceId}/member-profile/{userId}", summary: "Get a member's profile", group: "User" },
  { method: "PATCH", path: "/workspaces/{workspaceId}/member-profile/{userId}", summary: "Update a member's profile", group: "User" },
  { method: "GET", path: "/workspaces/{workspaceId}/users", summary: "Find all users on a workspace", group: "User" },
  { method: "POST", path: "/workspaces/{workspaceId}/users/info", summary: "Filter workspace users", group: "User" },
  { method: "PUT", path: "/workspaces/{workspaceId}/users/{userId}/custom-field/{customFieldId}/value", summary: "Update a user's custom field", group: "User" },
  { method: "GET", path: "/workspaces/{workspaceId}/users/{userId}/managers", summary: "Find user's team manager", group: "User" },
  { method: "DELETE", path: "/workspaces/{workspaceId}/users/{userId}/roles", summary: "Remove user's manager role", group: "User" },
  { method: "POST", path: "/workspaces/{workspaceId}/users/{userId}/roles", summary: "Give manager role to a user", group: "User" },
  { method: "GET", path: "/workspaces/{workspaceId}/addons/{addonId}/webhooks", summary: "Get all webhooks for addon on a workspace", group: "Webhooks" },
  { method: "GET", path: "/workspaces/{workspaceId}/webhooks", summary: "Get all webhooks on a workspace", group: "Webhooks" },
  { method: "POST", path: "/workspaces/{workspaceId}/webhooks", summary: "Create a webhook", group: "Webhooks" },
  { method: "DELETE", path: "/workspaces/{workspaceId}/webhooks/{webhookId}", summary: "Delete a webhook", group: "Webhooks" },
  { method: "GET", path: "/workspaces/{workspaceId}/webhooks/{webhookId}", summary: "Get a specific webhook by id", group: "Webhooks" },
  { method: "PUT", path: "/workspaces/{workspaceId}/webhooks/{webhookId}", summary: "Update a webhook", group: "Webhooks" },
  { method: "POST", path: "/workspaces/{workspaceId}/webhooks/{webhookId}/logs", summary: "Get logs for a webhook", group: "Webhooks" },
  { method: "GET", path: "/workspaces/{workspaceId}/webhooks/{webhookId}/statuses", summary: "Get webhook event statuses for a webhook", group: "Webhooks" },
  { method: "PATCH", path: "/workspaces/{workspaceId}/webhooks/{webhookId}/token", summary: "Generate a new token", group: "Webhooks" },
  { method: "GET", path: "/workspaces", summary: "Get all my workspaces", group: "Workspace" },
  { method: "POST", path: "/workspaces", summary: "Add a workspace", group: "Workspace" },
  { method: "GET", path: "/workspaces/{workspaceId}", summary: "Get workspace info", group: "Workspace" },
  { method: "PUT", path: "/workspaces/{workspaceId}/cost-rate", summary: "Update workspace cost rate", group: "Workspace" },
  { method: "PUT", path: "/workspaces/{workspaceId}/hourly-rate", summary: "Update workspace billable rate", group: "Workspace" },
  { method: "POST", path: "/workspaces/{workspaceId}/limited-users", summary: "Add limited users", group: "Workspace" },
  { method: "POST", path: "/workspaces/{workspaceId}/users", summary: "Add user to a workspace", group: "Workspace" },
  { method: "PUT", path: "/workspaces/{workspaceId}/users/{userId}", summary: "Update a user's status", group: "Workspace" },
  { method: "PUT", path: "/workspaces/{workspaceId}/users/{userId}/cost-rate", summary: "Update a user's cost rate", group: "Workspace" },
  { method: "PUT", path: "/workspaces/{workspaceId}/users/{userId}/hourly-rate", summary: "Update a user's hourly rate", group: "Workspace" },
  { method: "DELETE", path: "/workspaces/{workspaceId}/users/{userId}", summary: "Remove user from a workspace", group: "Workspace (Deprecated)" },
];
